spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 9898

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/