eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/academy
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


token-authen:
  secret-key: "C12L10A82R19A019ACA8219DE03MY"
  bearer: "Bearer "
  expiration: 2592000000L #60(Second) * 60(Munites) * 24(hours) * 30(days) * 1000L(milisecond - L is long)