eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/academy
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
