eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/academy
    username: root
    password: root

