server:
  port: 8671

spring:
  application:
    name: eureka-service


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8671/eureka
  server:
    enable-self-preservation: false